### ISSUE TITLE
Mention platforms in your readme.md file

### ISSUE THREAD

**Issue by glennawatson** [LukeMoody01/Moody.DialogService#1]
Takes quite a bit into your readme file without it mentioning the platform it supports mentioned.

**Comment by LukeMoody01** [comment]
Hi Glenn, thanks for pointing that out! 
I have addressed this with the following commit.

[Commit](https://github.com/LukeMoody01/Moody.DialogService/commit/b6175d108e9180e62bae3e159f00778661a4ea8d)
